language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

env:
  - COMPOSER_FLAGS='update --prefer-lowest --prefer-stable'
  - COMPOSER_FLAGS='install'

install:
  - composer $COMPOSER_FLAGS --prefer-dist --no-interaction

script: vendor/phpunit/phpunit/phpunit --verbose
